// Generated by CoffeeScript 2.4.1
(function () {
  document.getElementById('logo').innerHTML = "<div class=\"container flex-center full-height\">\n  <div class=\"notification\">\n    <p class=\"title\">Lines</p>\n    <p class=\"subtitle\">A new line every 250ms</p>\n  </div>\n</div>";

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibG9nby5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbImxvZ28uY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTtFQUFBLFFBQVEsQ0FBQyxjQUFULENBQXdCLE1BQXhCLENBQStCLENBQUMsU0FBaEMsR0FBNEM7QUFBNUMiLCJzb3VyY2VzQ29udGVudCI6WyJkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbG9nbycpLmlubmVySFRNTCA9IFwiXCJcIjxkaXYgY2xhc3M9XCJjb250YWluZXIgZmxleC1jZW50ZXIgZnVsbC1oZWlnaHRcIj5cbiAgICA8ZGl2IGNsYXNzPVwibm90aWZpY2F0aW9uXCI+XG4gICAgICA8cCBjbGFzcz1cInRpdGxlXCI+TGluZXM8L3A+XG4gICAgICA8cCBjbGFzcz1cInN1YnRpdGxlXCI+QSBuZXcgbGluZSBldmVyeSAyNTBtczwvcD5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG5cIlwiXCJcbiJdfQ==
//# sourceURL=logo.coffee
