// Generated by CoffeeScript 2.4.1
(function () {
  document.getElementById('nav').innerHTML = "<div class=\"container is-fluid\" style=\"padding-top: 1rem;padding-top: 1rem;\">\n  <nav class=\"breadcrumb\">\n    <ul>\n      <li class=\"is-active\"><a href=\"https://github.com/Beyarz/lines\">Github</a></li>\n      <li><a href=\"https://github.com/Beyarz/lines\">Beyarz</a></li>\n    </ul>\n  </nav>\n</div>";

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibmF2LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmF2LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7RUFBQSxRQUFRLENBQUMsY0FBVCxDQUF3QixLQUF4QixDQUE4QixDQUFDLFNBQS9CLEdBQTJDO0FBQTNDIiwic291cmNlc0NvbnRlbnQiOlsiZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ25hdicpLmlubmVySFRNTCA9IFwiXCJcIjxkaXYgY2xhc3M9XCJjb250YWluZXIgaXMtZmx1aWRcIiBzdHlsZT1cInBhZGRpbmctdG9wOiAxcmVtO3BhZGRpbmctdG9wOiAxcmVtO1wiPlxuICAgIDxuYXYgY2xhc3M9XCJicmVhZGNydW1iXCI+XG4gICAgICA8dWw+XG4gICAgICAgIDxsaSBjbGFzcz1cImlzLWFjdGl2ZVwiPjxhIGhyZWY9XCJodHRwczovL2dpdGh1Yi5jb20vQmV5YXJ6L2xpbmVzXCI+R2l0aHViPC9hPjwvbGk+XG4gICAgICAgIDxsaT48YSBocmVmPVwiaHR0cHM6Ly9naXRodWIuY29tL0JleWFyei9saW5lc1wiPkJleWFyejwvYT48L2xpPlxuICAgICAgPC91bD5cbiAgICA8L25hdj5cbiAgPC9kaXY+XG5cIlwiXCJcbiJdfQ==
//# sourceURL=nav.coffee
