// Generated by CoffeeScript 2.4.1
(function () {
  document.getElementById('nav').innerHTML = "<div class=\"container is-fluid\" style=\"padding-top: 1rem;padding-left: 1rem;\">\n  <nav class=\"breadcrumb\">\n    <ul>\n      <li class=\"is-active\"><a href=\"https://github.com/Beyarz/lines\">Github</a></li>\n      <li><a href=\"https://github.com/Beyarz/lines\">Beyarz</a></li>\n    </ul>\n  </nav>\n</div>";

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibmF2LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmF2LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7RUFBQSxRQUFRLENBQUMsY0FBVCxDQUF3QixLQUF4QixDQUE4QixDQUFDLFNBQS9CLEdBQTJDO0FBQTNDIiwic291cmNlc0NvbnRlbnQiOlsiZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ25hdicpLmlubmVySFRNTCA9IFwiXCJcIjxkaXYgY2xhc3M9XCJjb250YWluZXIgaXMtZmx1aWRcIiBzdHlsZT1cInBhZGRpbmctdG9wOiAxcmVtO3BhZGRpbmctbGVmdDogMXJlbTtcIj5cbiAgICA8bmF2IGNsYXNzPVwiYnJlYWRjcnVtYlwiPlxuICAgICAgPHVsPlxuICAgICAgICA8bGkgY2xhc3M9XCJpcy1hY3RpdmVcIj48YSBocmVmPVwiaHR0cHM6Ly9naXRodWIuY29tL0JleWFyei9saW5lc1wiPkdpdGh1YjwvYT48L2xpPlxuICAgICAgICA8bGk+PGEgaHJlZj1cImh0dHBzOi8vZ2l0aHViLmNvbS9CZXlhcnovbGluZXNcIj5CZXlhcno8L2E+PC9saT5cbiAgICAgIDwvdWw+XG4gICAgPC9uYXY+XG4gIDwvZGl2PlxuXCJcIlwiXG4iXX0=
//# sourceURL=nav.coffee
