// Generated by CoffeeScript 2.4.1
(function () {
  var prepend;

  prepend = (id, content) => {
    return document.getElementById(id).innerHTML = content;
  };

  prepend('nav', "<div class=\"container is-fluid\" style=\"padding-top: 1rem;padding-left: 1rem;\">\n  <nav class=\"breadcrumb\">\n    <ul>\n      <li class=\"is-active\"><a href=\"https://github.com/Beyarz/lines\">Github</a></li>\n      <li><a href=\"https://github.com/Beyarz/lines\">Beyarz</a></li>\n    </ul>\n  </nav>\n</div>");
  prepend('logo', "<div class=\"container flex-center full-height\">\n  <div class=\"notification\">\n    <p class=\"title\">Lines</p>\n    <p class=\"subtitle\">A new line every 250ms</p>\n  </div>\n</div>");
}).call(this);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInByZXBlbmQuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxDQUFBLFlBQUE7QUFBQSxNQUFBLE9BQUE7O0FBQUEsRUFBQSxPQUFBLEdBQVUsQ0FBQSxFQUFBLEVBQUEsT0FBQSxLQUFBO1dBQ1IsUUFBUSxDQUFSLGNBQUEsQ0FBQSxFQUFBLEVBQUEsU0FBQSxHQUF3QyxPO0FBRGhDLEdBQVY7O0FBR0EsRUFBQSxPQUFBLENBQUEsS0FBQSxFQUFBLDJUQUFBLENBQUE7QUFZQSxFQUFBLE9BQUEsQ0FBQSxNQUFBLEVBQUEsNkxBQUEsQ0FBQTtDQWZBLEUsSUFBQSxDLElBQUEiLCJzb3VyY2VzQ29udGVudCI6WyJwcmVwZW5kID0gKGlkLCBjb250ZW50KSA9PlxuICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChpZCkuaW5uZXJIVE1MID0gY29udGVudFxuXG5wcmVwZW5kKCduYXYnLFxuXCJcIlwiPGRpdiBjbGFzcz1cImNvbnRhaW5lciBpcy1mbHVpZFwiIHN0eWxlPVwicGFkZGluZy10b3A6IDFyZW07cGFkZGluZy1sZWZ0OiAxcmVtO1wiPlxuICAgIDxuYXYgY2xhc3M9XCJicmVhZGNydW1iXCI+XG4gICAgICA8dWw+XG4gICAgICAgIDxsaSBjbGFzcz1cImlzLWFjdGl2ZVwiPjxhIGhyZWY9XCJodHRwczovL2dpdGh1Yi5jb20vQmV5YXJ6L2xpbmVzXCI+R2l0aHViPC9hPjwvbGk+XG4gICAgICAgIDxsaT48YSBocmVmPVwiaHR0cHM6Ly9naXRodWIuY29tL0JleWFyei9saW5lc1wiPkJleWFyejwvYT48L2xpPlxuICAgICAgPC91bD5cbiAgICA8L25hdj5cbiAgPC9kaXY+XG5cIlwiXCJcbilcblxucHJlcGVuZCgnbG9nbycsXG5cIlwiXCI8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGZsZXgtY2VudGVyIGZ1bGwtaGVpZ2h0XCI+XG4gICAgPGRpdiBjbGFzcz1cIm5vdGlmaWNhdGlvblwiPlxuICAgICAgPHAgY2xhc3M9XCJ0aXRsZVwiPkxpbmVzPC9wPlxuICAgICAgPHAgY2xhc3M9XCJzdWJ0aXRsZVwiPkEgbmV3IGxpbmUgZXZlcnkgMjUwbXM8L3A+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuXCJcIlwiXG4pXG4iXSwic291cmNlUm9vdCI6IiJ9
//# sourceURL=prepend.coffee
