// Generated by CoffeeScript 2.4.1
(function() {
  var generate, generateNode, injectDom, rand, regenerate;

  generateNode = function(width, r, g, b) {
    var objectNode;
    objectNode = document.createElement('p');
    objectNode.className = 'round container';
    objectNode.style = 'border: 2px solid rgb(' + r + ', ' + g + ', ' + b + ')';
    objectNode.style.width = width + 'rem';
    return objectNode;
  };

  injectDom = function(object) {
    var app;
    app = document.getElementById('app-root');
    return app.appendChild(object);
  };

  rand = function(int, min) {
    return Math.floor(Math.random() * int) + min;
  };

  regenerate = function() {
    document.getElementById('app-root').childNodes[0].remove();
    return generate(2);
  };

  generate = function(amount) {
    var b, count, g, node, r, results, width;
    count = 1;
    results = [];
    while (count !== amount) {
      width = rand(24, 1);
      r = rand(255, 2);
      g = rand(255, 2);
      b = rand(255, 2);
      node = generateNode(width, r, g, b);
      injectDom(node);
      results.push(count++);
    }
    return results;
  };

  generate(rand(12, 6)) && setInterval(regenerate, 250);

}).call(this);

//# sourceMappingURL=script.js.map
