// Generated by CoffeeScript 2.4.1
(function() {
  // The root element where everything spawns within
  /*
    r = red
    g = green
    b = blue
  */
  var app, generate, generateNode, injectDom, rand, regenerate;

  app = document.getElementById('app-root');

  generateNode = function(width, r, g, b) {
    var objectNode;
    objectNode = document.createElement('p');
    objectNode.className = 'round container';
    objectNode.style = `border: 2px solid rgb(${r}, ${g}, ${b})`;
    objectNode.style.width = width + 'rem';
    return objectNode;
  };

  injectDom = function(object) {
    return app.appendChild(object);
  };

  rand = function(max, min) {
    return Math.floor(Math.random() * max) + min;
  };

  // Remove the first child and generate a new one
  regenerate = function() {
    app.childNodes[0].remove();
    return generate(2);
  };

  // Generates individual lines
  generate = function(amount) {
    var b, count, g, node, r, results, width;
    count = 1;
    results = [];
    while (count !== amount) {
      width = rand(24, 1);
      r = rand(255, 2);
      g = rand(255, 2);
      b = rand(255, 2);
      node = generateNode(width, r, g, b);
      injectDom(node);
      results.push(count++);
    }
    return results;
  };

  /*
  When the windows first loads generate a full set of random
  lines then start remove the first child and inject a freshly
  generated line
  */
  generate(rand(12, 6)) && setInterval(regenerate, 250);

  //# sourceMappingURL=script.js.map;

}).call(this);

//# sourceMappingURL=script.js.map
